compatibility_date ="2024-04-25"
name = "wedding"
pages_build_output_dir= "./build"
kv_namespaces = [
    { binding = "WEDDING", id = "63e6efce6ad0435fa17e8ada66fc7904" }
]
d1_databases = [
    {binding = "DB", database_name = "wedding", database_id = "04a5a541-e119-41d9-b249-7d2e16ff49c9"}
]
r2_buckets = [
    {binding = 'R2', bucket_name = "wedding"}
]